### ISSUE TITLE
Windows -ip from other drives & drive letters in path

### ISSUE THREAD

**Issue by WaGi-Coding** [nerdyrodent/VQGAN-CLIP#129]
Hey there. Unfortunately on Windows, for the imageprompt -ip argument, i cannot use pathts containing a drive letter. So i cannot work with images from another drive or use the path string without normalizing it.

For the initial image -ii it works fine, as the python script handles that.

But for -ip with my paths like "C:\savedimages\image1.jpg" or "D:\savedimages\image1.jpg" it won't work. However i could use image1.jpg from C: with "/savedimages/image1.jpg"

If i use the ones with drive letters i get following error:

`Traceback (most recent call last):
  File "C:\Users\Taki\VQGAN-CLIP\generate.py", line 637, in <module>
    path, weight, stop = split_prompt(prompt)
  File "C:\Users\Taki\VQGAN-CLIP\generate.py", line 300, in split_prompt
    return vals[0], float(vals[1]), float(vals[2])
ValueError: could not convert string to float: '\\savedimages\\image1.jpg'`

Is there any way it could get fixed in the script? Or is there any way to pass the path via the cmd in a way the script will interpret it correctly?

Greetings from Vienna

**Comment by WaGi-Coding** [comment]
The same problem happens with -ip using URLs

**Comment by WaGi-Coding** [comment]
Yeh, thats why i made this issue ^^
