### ISSUE TITLE
-conf and -ckpt argument question | use other models

### ISSUE THREAD

**Issue by felixbro** [nerdyrodent/VQGAN-CLIP#130]
Hello there, i have a issue with the -conf and -ckpt arguments:
i would like to use another model but how do i use them?
i type this in the Anaconda Promt:
`python generate.py -p "man by Peter Paul Rubens" -ii samples/fb.jpg -i 1200 -se 10 -o output/output6.png -conf checkpoints/faceshq.yaml -ckpt checkpoints/faceshq.ckpt`

facehq.yaml and facehq.ckpt are in the checkpoints folder. i only get this error:

(vqgan) d:\AI_Images\VQGAN-CLIP>python generate.py -p "man by Peter Paul Rubens" -ii samples/fb.jpg -i 1200 -se 10 -o output/output6.png -conf checkpoints/faceshq.yaml -ckpt checkpoints/faceshq.ckpt
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
Traceback (most recent call last):
  File "d:\AI_Images\VQGAN-CLIP\generate.py", line 546, in <module>
    model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
  File "d:\AI_Images\VQGAN-CLIP\generate.py", line 527, in load_vqgan_model
    parent_model = cond_transformer.Net2NetTransformer(**config.model.params)
  File "d:\AI_Images\VQGAN-CLIP\taming-transformers\taming\models\cond_transformer.py", line 41, in __init__
    self.transformer = instantiate_from_config(config=transformer_config)
  File "d:\AI_Images\VQGAN-CLIP\taming-transformers\main.py", line 119, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "d:\AI_Images\VQGAN-CLIP\taming-transformers\main.py", line 22, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\Users\fb\Anaconda3\envs\vqgan\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\AI_Images\VQGAN-CLIP\taming-transformers\taming\modules\transformer\mingpt.py", line 17, in <module>
    from transformers import top_k_top_p_filtering
ModuleNotFoundError: No module named 'transformers'

i only have a `D:\AI_Images\VQGAN-CLIP\taming-transformers\taming\modules\transformer` folder, not transformers
what can i do?

**Comment by WaGi-Coding** [comment]
I had the same issue for a range of different models. It was driving me crazy. The issue is the difference between the official python pip package for taming-transformers and the github repo. It's solved by installing the github version.
```
pip install transformers
pip uninstall taming-transformers
pip install git+https://github.com/CompVis/taming-transformers
```
This should work for:
Ade20k
CelebAHQ
Cin
Coco
Drin
FacesHQ
FFHQ
Gumbel
Imagenet_1024
Imagenet_16384
SFlckr
Wikiart

_Originally posted by @GucciFlipFlops1917 in https://github.com/nerdyrodent/VQGAN-CLIP/issues/106#issuecomment-1003419726_

**Comment by GoddessFreya13** [comment]
I was having the same problem and have gotten it to work correctly. To use other models, you have to have their .yaml and .ckpt files in the checkpoint folder. When passing the -ckpt, use the argument of the name of the model.ckpt. 
For example, I have downloaded all the models that I can find for the VQGAN+CLIP. To get the coco model to work I have to pass "-ckpt checkpoints\coco.ckpt".
