### ISSUE TITLE
RuntimeError: PytorchStreamReader

### ISSUE THREAD

**Issue by Nyexaas** [nerdyrodent/VQGAN-CLIP#149]
Hello, after fix few errors by myself i tryed to do a test but an error happen and i can't fix the last one here is the error : 

(vqgan) C:\Users\Nyexa\VQGAN-CLIP>python generate.py -p "Black art cathedral"
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips\vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Traceback (most recent call last):
  File "C:\Users\Nyexa\VQGAN-CLIP\generate.py", line 546, in <module>
    model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
  File "C:\Users\Nyexa\VQGAN-CLIP\generate.py", line 520, in load_vqgan_model
    model.init_from_ckpt(checkpoint_path)
  File "C:\Users\Nyexa\VQGAN-CLIP\taming-transformers\taming\models\vqgan.py", line 45, in init_from_ckpt
    sd = torch.load(path, map_location="cpu")["state_dict"]
  File "C:\Users\Nyexa\anaconda3\envs\vqgan\lib\site-packages\torch\serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Nyexa\anaconda3\envs\vqgan\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Nyexaas** [comment]
I found a solution, i downloaded everything again and also after write : cd VQGAN-CLIP
