### ISSUE TITLE
No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by sidhomj** [nerdyrodent/VQGAN-CLIP#21]
When I run the generate.py script, I get the following error when the video is being made.

```
Generating video...
Traceback (most recent call last):
  File "/home/ubuntu/VQGAN-CLIP/generate.py", line 581, in <module>
    p = Popen(['ffmpeg',
  File "/home/ubuntu/anaconda3/envs/vqgan/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/anaconda3/envs/vqgan/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by nerdyrodent** [comment]
I'd guess that you don't have ffmpeg installed? I've got ffmpeg installed via apt, though it would probably work via conda etc too.
