### ISSUE TITLE
Can't generate video

### ISSUE THREAD

**Issue by Vanceagher** [nerdyrodent/VQGAN-CLIP#26]
I get this error when using -vid
```Generating video...
Traceback (most recent call last):
  File "C:\Users\vanceagher\vqgan\generate.py", line 669, in <module>
    p = Popen(['ffmpeg',
  File "C:\Users\vanceagher\anaconda3\envs\vqgan\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\vanceagher\anaconda3\envs\vqgan\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified````

**Comment by Vanceagher** [comment]
Closed after I installed FFmpeg using https://www.wikihow.com/Install-FFmpeg-on-Windows
