### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by alexpottt** [nerdyrodent/VQGAN-CLIP#60]
`(base) PS C:\Users\Alex\vqgan-clip> python generate.py -p "A painting of an apple in a fruit bowl"
Traceback (most recent call last):
  File "generate.py", line 546, in <module>
    model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
  File "generate.py", line 516, in load_vqgan_model
    config = OmegaConf.load(config_path)
  File "C:\Users\Alex\anaconda3\lib\site-packages\omegaconf\omegaconf.py", line 184, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\Alex\anaconda3\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\Alex\vqgan-clip\checkpoints\vqgan_imagenet_f16_16384.yaml", line 43, column 15
(base) PS C:\Users\Alex\vqgan-clip>`

**Comment by alexpottt** [comment]
Using vqgan_imagenet_f16_16384.yaml

**Comment by alexpottt** [comment]
Any thoughts would be great.

**Comment by alexpottt** [comment]
I solved it. It appears that there is an issue with the formatting of the .yaml file when you use `curl -L -o checkpoints/vqgan_imagenet_f16_16384.yaml -C - 'https://heibox.uni-heidelberg.de/d/a7530b09fed84f80a887/files/?p=%2Fconfigs%2Fmodel.yaml&dl=1' #ImageNet 16384` to install.

I fixed this issue by downloading .yaml file manually  from link and dropping it into checkpoints dir
