### ISSUE TITLE
requires_grad_ is not supported on ScriptModules

### ISSUE THREAD

**Issue by julianallchin** [nerdyrodent/VQGAN-CLIP#65]
using cuda 11.2, built torch from source

```
Traceback (most recent call last):
  File "/home/julianallchin/github/VQGAN-CLIP/generate.py", line 548, in <module>
    perceptor = clip.load(args.clip_model, jit=jit)[0].eval().requires_grad_(False).to(device)
  File "/home/julianallchin/anaconda3/envs/vqgan/lib/python3.9/site-packages/torch/jit/_script.py", line 915, in fail
    raise RuntimeError(name + " is not supported on ScriptModules")
RuntimeError: requires_grad_ is not supported on ScriptModules

```

**Comment by utkusen** [comment]
I have the same problem

**Comment by SirWaffle** [comment]
I am also seeing the same issue with pytorch 1.10.0, any suggestions that dont involve reverting to an older version?

**Comment by nerdyrodent** [comment]
While it does work with Pytorch > 1.9.1, the line for detecting the Pytorch does not. Jit should only really be true when using 1.7.1
