### ISSUE TITLE
Error build_model

### ISSUE THREAD

**Issue by cgob** [nerdyrodent/VQGAN-CLIP#97]
Hello,

I have an issue with the loading of the clip model. I have tried different arguments but I alway get the same issue.
```
(vqgan) python generate.py -p "Apple on a table"

Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips\vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Restored from checkpoints/vqgan_imagenet_f16_16384.ckpt
Traceback (most recent call last):
  File "VQGAN-CLIP\generate.py", line 549, in <module>
    perceptor = clip.load(args.clip_model, jit=jit)[0].eval().requires_grad_(False).to(device)
  File "VQGAN-CLIP\CLIP\clip\clip.py", line 135, in load
    model = build_model(state_dict or model.state_dict()).to(device)
  File "VQGAN-CLIP\CLIP\clip\model.py", line 396, in build_model
    vit = "visual.proj" in state_dict
  File "D:\cond\envs\vqgan\lib\site-packages\torch\jit\_script.py", line 733, in __contains__
    return self.forward_magic_method("__contains__", key)
  File "D:\cond\envs\vqgan\lib\site-packages\torch\jit\_script.py", line 720, in forward_magic_method
    raise NotImplementedError()
NotImplementedError
```

Thank you 

Cédric

**Comment by nerdyrodent** [comment]
Which PyTorch did you install?

**Comment by cgob** [comment]
I used:
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by nerdyrodent** [comment]
jit should be false then, so it shouldn't be that. My guess would be that a requirement isn't installed.
