### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by ggml** [nerdyrodent/VQGAN-CLIP#98]
hi:: noob here, could use a hint about cause of this errors ::thank you
congrats for your work!

(vqgan) D:\github\VQGAN-CLIP>python generate.py -p "Apple on a table"
Traceback (most recent call last):
  File "D:\github\VQGAN-CLIP\generate.py", line 546, in <module>
    model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
  File "D:\github\VQGAN-CLIP\generate.py", line 516, in load_vqgan_model
    config = OmegaConf.load(config_path)
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\omegaconf\omegaconf.py", line 184, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\ggml\anaconda3\envs\vqgan\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\github\VQGAN-CLIP\checkpoints\vqgan_imagenet_f16_16384.yaml", line 43, column 15

**Comment by nerdyrodent** [comment]
There aren't 43 lines in vqgan_imagenet_f16_16384.yaml. I'd suggest using the correct .yaml file
